### ISSUE TITLE
d100% is only rolling d100

### ISSUE THREAD

**Issue by achetzel** [ParticulaCode/FoundryVTT-GoDice#5]
First of all thanks for your work on this. I have been holding off on bluetooth dice for a while and though there are some quirks with the system I'm very excited to see how far along it's come. 

I'm using Foundry 11.302 and WFRP 6.5.9. 

The entire system is either d10 or d100. 

When a call is made to roll d100%, the GoDice companion only calls for the d100. Thus, all results are only 10s value of 10, 20, 30, etc. The expected outcome would be to roll d100 + d10 and have a true percentage shown.

**Comment by Geek5510** [comment]
This should be solved with the latest pull request (#9).

**Comment by ParticulaCode** [comment]
A new update (with the fix) was just released.

**Comment by achetzel** [comment]
Totally works! Thanks so much! It also seems to have resolved: https://github.com/ParticulaCode/FoundryVTT-GoDice/issues/6

**Comment by achetzel** [comment]
Fixed

**Comment by cojinx303** [comment]
This is still happening, trying to test in Imperium Maledictum, Call of Cthulhu, Delta Green, and WFRP, all will prompt (and produce) only the d100 roll. Displays the d100 10's place but not a separate d10 1's place even if a d10 is rolled simultaneously.
